version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mendeit/foodgram_backend
    container_name: foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/mediafiles/
    depends_on:
      - db

  frontend:
    image: mendeit/foodgram_frontend
    container_name: foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: mendeit/foodgram_gateway
    container_name: foodgram_gateway
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/foodgram/static/
      - media:/var/www/foodgram/media/
      - ./docs/openapi-schema.yml:/var/www/foodgram/redoc/openapi-schema.yml
      - ./docs/redoc.html:/var/www/foodgram/redoc/redoc.html
    depends_on:
      - frontend
      - backend
    ports:
      - 8500:80
