version: '3'

volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/mediafiles/
    depends_on:
      - db

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    env_file: .env
    volumes:
      - frontend_static:/app/result_build/

  gateway:
    build:
        context: ./gateway
        dockerfile: Dockerfile
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend_static:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/build:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
    ports:
      - 8000:80
