name: Foodgram Production workflow

on:
  workflow_run:
    workflows: CI
    types:
      - completed

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  backend_build_and_push_to_docker_hub:
    name: Push Docker backend image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - automated-api-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}} 
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/foodgram_backend:latest

  frontend_build_and_push_to_docker_hub:
    name: Push Docker frontend image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - automated-api-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/foodgram_frontend:latest

  gateway_build_and_push_to_docker_hub:
    name: Push Docker gateway image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - automated-api-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./gateway/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway:latest

  deploy:
    name: Push Docker images to HOST
    runs-on: ubuntu-latest
    needs: 
      - backend_build_and_push_to_docker_hub
      - frontend_build_and_push_to_docker_hub
      - gateway_build_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.YANDEX_PRACTICUM_VM_HOST }}
          username: ${{ secrets.YANDEX_PRACTICUM_VM_USER }}
          key: ${{ secrets.YANDEX_PRACTICUM_VM_SSH_KEY }}
          passphrase: ${{ secrets.YANDEX_PRACTICUM_VM_SSH_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "foodgram"

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YANDEX_PRACTICUM_VM_HOST }}
          username: ${{ secrets.YANDEX_PRACTICUM_VM_USER }}
          key: ${{ secrets.YANDEX_PRACTICUM_VM_SSH_KEY }}
          passphrase: ${{ secrets.YANDEX_PRACTICUM_VM_SSH_PASSPHRASE }}
          script: |
            cd foodgram
            make deploy
            make cleanhost

  send_telegram_message:
    runs-on: ubuntu-latest
    name: Send message to telegram
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: <<${{github.ref_name}}>> Автор <<${{ github.actor }}>> добавил изменения в <<${{github.repository}}>>. Деплой успешно выполнен!
